//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_OrderStudent
    {
        public int ID { get; set; }
        public string OrderId { get; set; }
        public int BookerId { get; set; }
        public int TraineeId { get; set; }
        public string TraineeName { get; set; }
        public string TraineeCRMCId { get; set; }
        public int ResourceId { get; set; }
        public Nullable<System.DateTime> StudyDate { get; set; }
        public Nullable<int> StudyStatus { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public bool IsActive { get; set; }
        public string Remark { get; set; }
    }
}
