//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_ApiAccount
    {
        public int ID { get; set; }
        public string AccountId { get; set; }
        public string AccountKey { get; set; }
        public string LimitIP { get; set; }
        public string Name { get; set; }
        public string ApiType { get; set; }
        public bool IsActivity { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ExpireTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
