//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_StudyHistory
    {
        public int ID { get; set; }
        public int TraineeId { get; set; }
        public int ResourceId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string CourseName { get; set; }
        public string City { get; set; }
        public string StudyWay { get; set; }
        public Nullable<int> StudySeconds { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> StudyTime { get; set; }
        public Nullable<int> StudyStatus { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Remark { get; set; }
    }
}
