//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_UserLog
    {
        public int ID { get; set; }
        public string TableName { get; set; }
        public int TableId { get; set; }
        public System.DateTime LogDate { get; set; }
        public int UserId { get; set; }
        public string Operation { get; set; }
        public string Comment { get; set; }
    }
}
