//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_SalesAllot
    {
        public long ID { get; set; }
        public int ResourceId { get; set; }
        public int SalesId { get; set; }
        public string Name { get; set; }
        public string PrivateCode { get; set; }
        public string QrCode { get; set; }
        public bool IsEnable { get; set; }
        public int SortId { get; set; }
        public int ChangeCount { get; set; }
        public int TermCount { get; set; }
        public Nullable<int> PostCount { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> ExpireTime { get; set; }
    }
}
