//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_WechatPay
    {
        public long ID { get; set; }
        public string appid { get; set; }
        public string mch_id { get; set; }
        public string device_info { get; set; }
        public string nonce_str { get; set; }
        public string sign { get; set; }
        public string sign_type { get; set; }
        public string result_code { get; set; }
        public string err_code { get; set; }
        public string err_code_des { get; set; }
        public string openid { get; set; }
        public string is_subscribe { get; set; }
        public string trade_type { get; set; }
        public string bank_type { get; set; }
        public int total_fee { get; set; }
        public Nullable<int> settlement_total_fee { get; set; }
        public string fee_type { get; set; }
        public int cash_fee { get; set; }
        public string cash_fee_type { get; set; }
        public Nullable<int> coupon_fee { get; set; }
        public Nullable<int> coupon_count { get; set; }
        public string coupon_type { get; set; }
        public string coupon_id { get; set; }
        public Nullable<int> coupon_feen { get; set; }
        public string transaction_id { get; set; }
        public string out_trade_no { get; set; }
        public string attach { get; set; }
        public string time_end { get; set; }
        public Nullable<System.DateTime> Pay_Time { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public Nullable<bool> Is_Synced { get; set; }
        public Nullable<System.DateTime> Sync_Time { get; set; }
        public string Remark { get; set; }
    }
}
