//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Register
    {
        public int ID { get; set; }
        public string OrderId { get; set; }
        public int UserId { get; set; }
        public string CRMCId { get; set; }
        public string UserName { get; set; }
        public int ResourceType { get; set; }
        public int ResourceId { get; set; }
        public string ResourceName { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public string PayStatue { get; set; }
        public string PayWay { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string City { get; set; }
        public string Img { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public bool IsActive { get; set; }
        public string Remark { get; set; }
    }
}
