//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_UserRecord
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public string CompanyName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string TrainName { get; set; }
        public Nullable<int> TrainDay { get; set; }
        public Nullable<int> TrainNum { get; set; }
        public string CompanyAddress { get; set; }
        public string PostCode { get; set; }
        public string PublicName { get; set; }
        public string InHouseName { get; set; }
        public string InvalidRemark { get; set; }
        public Nullable<int> FromId { get; set; }
        public string TrainDate { get; set; }
        public string TrainDepart { get; set; }
        public string CrmOppId { get; set; }
        public string CrmOpportunityId { get; set; }
        public string OppName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string HandleUser { get; set; }
        public Nullable<System.DateTime> HandleDate { get; set; }
        public Nullable<int> IsSendEMail { get; set; }
        public Nullable<System.DateTime> SendEMailDate { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public int StatusId { get; set; }
        public string MediaSource { get; set; }
        public string MediaChildSource { get; set; }
        public string MediaRemark { get; set; }
        public Nullable<int> Clue { get; set; }
        public string OppStage { get; set; }
        public Nullable<double> OrderPrice { get; set; }
        public Nullable<System.DateTime> OrderSearchDate { get; set; }
        public Nullable<int> IsHandel { get; set; }
        public string SalesRemark { get; set; }
        public Nullable<double> OrderPriceNoTax { get; set; }
        public string Ip { get; set; }
        public string Url { get; set; }
        public System.DateTime ImportDate { get; set; }
        public Nullable<int> IsConfirmEvent { get; set; }
        public Nullable<int> IsSynchMktMember { get; set; }
        public string SplitOrdType { get; set; }
        public Nullable<int> IsSplit { get; set; }
        public Nullable<int> IsSplitHandel { get; set; }
        public string SplitMonth { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public string StuCrmOrderId { get; set; }
        public Nullable<int> IsLowIntention { get; set; }
        public string ImportUser { get; set; }
        public Nullable<int> ActiveMonth { get; set; }
        public string MediaNo { get; set; }
        public string MediaL1 { get; set; }
        public string MediaL2 { get; set; }
        public string MediaName { get; set; }
        public string PostName { get; set; }
        public string PostUnit { get; set; }
        public string AdContent { get; set; }
        public string AdPage { get; set; }
        public string AdPageType { get; set; }
        public string AdGroup { get; set; }
        public string ProductName { get; set; }
        public string City { get; set; }
        public byte IsActive { get; set; }
        public string Remark { get; set; }
    }
}
