//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_OrderSS
    {
        public int ID { get; set; }
        public string OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UnionId { get; set; }
        public string OpenId { get; set; }
        public string UserName { get; set; }
        public string BuyerId { get; set; }
        public string BuyerLogId { get; set; }
        public Nullable<int> SalesId { get; set; }
        public Nullable<int> Introducer { get; set; }
        public int ResourceId { get; set; }
        public int ResourceType { get; set; }
        public string Title { get; set; }
        public string PurchaseName { get; set; }
        public int Price { get; set; }
        public Nullable<int> CashPay { get; set; }
        public Nullable<int> CardPay { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> PaidAmount { get; set; }
        public Nullable<int> NoPaidAmount { get; set; }
        public Nullable<int> NoInvoiced { get; set; }
        public Nullable<int> InvoicedAmount { get; set; }
        public string ShowCity { get; set; }
        public string ShowAddress { get; set; }
        public Nullable<System.DateTime> ShowTime { get; set; }
        public int OrderStatus { get; set; }
        public Nullable<int> AuditStatus { get; set; }
        public Nullable<int> PayStatus { get; set; }
        public string PayId { get; set; }
        public string PayWay { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public Nullable<System.DateTime> RefundTime { get; set; }
        public Nullable<System.DateTime> SettleTime { get; set; }
        public Nullable<System.DateTime> ExpireTime { get; set; }
        public string ClientType { get; set; }
        public string UserPhone { get; set; }
        public string UserMail { get; set; }
        public string Creator { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public string Remark { get; set; }
        public string Reserve1 { get; set; }
        public string Reserve2 { get; set; }
        public string Reserve3 { get; set; }
        public string Reserve4 { get; set; }
        public Nullable<int> Reserve5 { get; set; }
        public Nullable<int> PayChannel { get; set; }
        public bool IsActive { get; set; }
    }
}
