//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_UserCalender
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string OrderId { get; set; }
        public Nullable<int> EventType { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public string Title { get; set; }
        public string Img { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> StudyTime { get; set; }
        public string City { get; set; }
        public string Place { get; set; }
        public Nullable<int> CheckStatus { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Remark { get; set; }
    }
}
