//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_AliPay
    {
        public long ID { get; set; }
        public System.DateTime notify_time { get; set; }
        public string notify_type { get; set; }
        public string notify_id { get; set; }
        public string app_id { get; set; }
        public string charset { get; set; }
        public string version { get; set; }
        public string sign_type { get; set; }
        public string sign { get; set; }
        public string trade_no { get; set; }
        public string out_trade_no { get; set; }
        public string out_biz_no { get; set; }
        public string buyer_id { get; set; }
        public string buyer_logon_id { get; set; }
        public string seller_id { get; set; }
        public string seller_email { get; set; }
        public string trade_status { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<decimal> receipt_amount { get; set; }
        public Nullable<decimal> invoice_amount { get; set; }
        public Nullable<decimal> buyer_pay_amount { get; set; }
        public Nullable<decimal> point_amount { get; set; }
        public Nullable<decimal> refund_fee { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public Nullable<System.DateTime> gmt_create { get; set; }
        public Nullable<System.DateTime> gmt_payment { get; set; }
        public Nullable<System.DateTime> gmt_refund { get; set; }
        public Nullable<System.DateTime> gmt_close { get; set; }
        public string fund_bill_list { get; set; }
        public string passback_params { get; set; }
        public string voucher_detail_list { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public Nullable<bool> Is_Synced { get; set; }
        public Nullable<System.DateTime> Sync_Time { get; set; }
        public string Remark { get; set; }
    }
}
