//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Video
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string MetaKeyWords { get; set; }
        public string MetaDesc { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Speaker { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Url { get; set; }
        public string Img { get; set; }
        public Nullable<int> IsReg { get; set; }
        public string BigImg { get; set; }
        public Nullable<int> CourseId { get; set; }
    }
}
