//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_OrderAllot
    {
        public long ID { get; set; }
        public string OrderId { get; set; }
        public int ResourceId { get; set; }
        public int SalesId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UnionId { get; set; }
        public string OpenId { get; set; }
        public string BuyerId { get; set; }
        public string BuyerLogId { get; set; }
        public string UserName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public string Remark { get; set; }
        public Nullable<int> PaidAmount { get; set; }
    }
}
