//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_LiveBook
    {
        public int ID { get; set; }
        public int LiveId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> BookTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string LiveUrl { get; set; }
        public string RePlayUrl { get; set; }
        public bool HasRePlay { get; set; }
        public bool HasLive { get; set; }
        public bool HasWPush { get; set; }
        public bool HasSms { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Reserve1 { get; set; }
    }
}
