//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_SMS
    {
        public long ID { get; set; }
        public string SmsKey { get; set; }
        public string SmsType { get; set; }
        public string WorkDate { get; set; }
        public string Phone { get; set; }
        public string ValCode { get; set; }
        public string Content { get; set; }
        public bool IsVerify { get; set; }
        public bool IsSended { get; set; }
        public bool IsSuccess { get; set; }
        public int RetryTime { get; set; }
        public string BackContent { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ExpireTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
