//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_UserNotice
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string NoticeType { get; set; }
        public string NoticeContent { get; set; }
        public Nullable<System.DateTime> NoticeTime { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Remark { get; set; }
    }
}
