//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Account
    {
        public int ID { get; set; }
        public string AccountID { get; set; }
        public string Name { get; set; }
        public string RecordType { get; set; }
        public int OwnerID { get; set; }
        public string CRMAccountId { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> CardAmount { get; set; }
        public Nullable<int> RemainBalance { get; set; }
        public string AccountStatus { get; set; }
        public string UserName { get; set; }
        public string UserPhone { get; set; }
        public string UserMail { get; set; }
        public string SalesName { get; set; }
        public string SalesId { get; set; }
        public string SalesCRMUserId { get; set; }
        public string SalesMail { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> ExpireTime { get; set; }
        public bool IsEnable { get; set; }
        public string Remark { get; set; }
    }
}
