//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_UserInfo
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public string Name { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Department { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> AllowLogin { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> DateOfLastLogin { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> HandleUser { get; set; }
        public Nullable<System.DateTime> HandleDate { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> IsSendEmail { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> SendEmailDate { get; set; }
        public Nullable<int> HandleStatusId { get; set; }
        public Nullable<int> FromId { get; set; }
        public Nullable<int> IsActiveEmail { get; set; }
        public System.DateTime DateOfUpdate { get; set; }
        public string CheckCode { get; set; }
        public int IsNew { get; set; }
        public string WebChatNo { get; set; }
        public int IsAccountEmail { get; set; }
        public Nullable<System.DateTime> UnBindWxDate { get; set; }
        public string UnionId { get; set; }
        public string WxHeadImg { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> IsCardMember { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<int> IsNewContact { get; set; }
        public Nullable<int> IsSalesOfNewCustomer { get; set; }
        public string CrmCompanyId { get; set; }
        public string CrmContactId { get; set; }
        public string CrmAccountNum { get; set; }
        public Nullable<System.DateTime> CrmAccountCreateDate { get; set; }
        public string CrmAccountCreateUser { get; set; }
        public Nullable<int> temp { get; set; }
        public string HashPwd { get; set; }
        public Nullable<int> IsNewAccount { get; set; }
        public string NickName { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Language { get; set; }
        public byte IsActive { get; set; }
        public string Remark { get; set; }
    }
}
